project:
  type: book
  output-dir: docs
  preview:
    port: 7035

lang: ru
metadata-files:
  - _metadata.yml

book:
  title: "RS ANDAN // PSY HSE"
  subtitle: "НИС «Прикладной анализ данных в психологии»"
  author:
    - name: "А. Ангельгардт"
      affiliations:
        - name: "НИУ ВШЭ // Департамент психологии"
  date: today
  chapters:
    - index.qmd
    - chpts/intro-basics.qmd
    - chpts/rpy-basics.qmd
    - chpts/prob-randvals.qmd
    # - chpts/rpy-data.qmd
    # - chpts/rpy-tidybase.qmd
    # - chpts/rpy-tidyadv.qmd
    # - chpts/rpy-strdt.qmd
    # - chpts/rpy-vis.qmd
    # - chpts/stats-desc.qmd
    # - chpts/stats-norm.qmd
    # - chpts/stats-cltci.qmd
    # - chpts/stats-hyptest.qmd
    # - chpts/andan-chisq.qmd
    # - chpts/stats-freqpval.qmd
    # - chpts/andan-cor.qmd
    # - chpts/andan-lm.qmd
    # - chpts/andan-lmx.qmd
    # - chpts/andan-owanova.qmd
    # - chpts/andan-twanova.qmd
    # - chpts/andan-rmanova.qmd
    # - chpts/andan-nonparam.qmd
    # - chpts/andan-glmlog.qmd
    # - chpts/andan-ml.qmd
    # - chpts/andan-efa.qmd
    # - chpts/andan-cfa.qmd
    # - chpts/andan-clust.qmd
    # - references.qmd

# bibliography: references.bib

lightbox: true

format:
  html:
    theme:
      - minty
      - style/custom.scss
