---
title: "SHAREXP | Codebook"
subtitle: "Описание датасетов и переменных"
output: html_document
---

## Описание эксперимента

В исследовании изучался зрительный поиск иконок различных платформ смартфонов.

> Цель исследования: выяснить, какая иконка «поделиться» (share) обознается лучше --- быстрее и точнее.

Испытуемым необходимо было искать иконки поделиться (share) iOS и Android среди дистракторов --- других иконок, которые для обеих платформ отрисованы одинаково.

**Независимые переменные исследования**:

- тип иконки --- иконка iOS (Outgoing Tray) и иконка Android (Three Dots)
- количество стимулов в пробе --- 8, 12, 16
- используемая платформа смартфона --- iOS или Android

Последняя переменная является квазиэкспериментальной.

В дизайн эксперимента были включены пробы с одним целевым стимулом (Outgoing Tray *или* Three Dots) и с двумя целевыми стимулами (*и* Outgoing Tray, *и* Three Dots)

**Зависимые переменные исследования**:

- время поиска целевого стимула (время реакции) --- от начала пробы до клика испытуемого
- точность поиска целевого стимула --- рассчитываемая через координаты клика


## Датасеты

### `sharexp_raw.zip`

Архив содержит аутпуты PsychoPy для каждого испытуемого. Все аутпуты генерируется программно и имеют одинаковую структуру.

Датасет содержит следующие переменные:

|Переменная|Значения|Описание|
|:---|:---|:---|
|`stim1`---`stim16`|Строка|Название графического файла со стимулом|
|`pos1`---`pos16`|Пара числовых значений|Позиция стимула на экране|
|`size1`---`size16`|Пара числовых значений|Размер стимула|
|`ok`|Строка|Название графического файла с кнопкой `OK`|
|`posok`|Пара числовых значений|Позиция кнопки `OK`|
|`sizeok`|Пара числовых значений|Размер кнопки `OK`|
|`numtrial`|Число|Номер пробы|
|`setsize`|Число (`8`, `12`, `16`)|Количество стимулов в пробе|
|`trialtype`|`tray` --- Outgoing Tray<br>`dots` --- Three Dots<br>`both` --- два целевых стимула|Тип пробы (целевой стимул)|
|`mouse_main1.time_raw`|Число|Время до первого клика (сек)|
|`mouse_main1.x_raw`|Число|Горизонтальная координата первого клика (px)|
|`mouse_main1.y_raw`|Число|Вертикальная координата первого клика (px)|
|`mouse_main2.time_raw`|Число|Время до второго клика (сек)|
|`mouse_main2.x_raw`|Число|Горизонтальная координата второго клика (px)|
|`mouse_main2.y_raw`|Число|Вертикальная координата второго клика (px)|
|`order`|Число|Порядок предъявления проб в конкретной сессии|

Переменные, отсутствующие в списке, не являются существенными для анализа и несут, скорее, техническую информацию.


> **NB!** В последних строках каждого файла записана социально-демографическая информация об испытуемом и техническая информация о сессии эксперимента.

### `targetpositions.xlsx`

Датасет содержит информацию о координатах целевых стимулов и диапазонах координат, в пределах которых клик считается корректным. У колонок, относящихся к тренировочной серии, в названии содержится аффикс `tr`.

|Переменная|Значения|Описание|
|:---|:---|:---|
|`posx1`|Число|Позиция первого целевого стимула по горизонтальной оси|
|`posy1`|Число|Позиция первого целевого стимула по вертикальной оси|
|`posxmin1`|Число|Минимальная координата клика по горизонтальной оси для первого целевого стимула|
|`posxmax1`|Число|Максимальная координата клика по горизонтальной оси для первого целевого стимула|
|`posymin1`|Число|Минимальная координата клика по вертикальной оси для первого целевого стимула|
|`posymax1`|Число|Максимальная координата клика по вертикальной оси для первого целевого стимула|
|`posx2`|Число|Позиция второго целевого стимула по горизонтальной оси|
|`posy2`|Число|Позиция второго целевого стимула по вертикальной оси|
|`posxmin2`|Число|Минимальная координата клика по горизонтальной оси для второго целевого стимула|
|`posxmax2`|Число|Максимальная координата клика по горизонтальной оси для второго целевого стимула|
|`posymin2`|Число|Минимальная координата клика по вертикальной оси для второго целевого стимула|
|`posymax2`|Число|Максимальная координата клика по вертикальной оси для второго целевого стимула|
|`numtrial`|Число|Номер пробы|


### `share_platform.csv`

Датасет содержит информацию об используемой респондентом платформе. Данные расположены [по ссылке](https://raw.githubusercontent.com/angelgardt/rs-app-andan-book/refs/heads/master/data/sharexp/share_platform.csv).

Датасет содержит следующие переменные:

|Переменная|Значения|Описание|Примечание|
|:---|:---|:---|:---|
|`id`|Число|Идентификатор испытуемого|Совпадает с названием файла в `sharexp_raw.zip`|
|`platform`|`ios` --- iOS<br>`andr` --- Androind|Платформа смартфона испытуемого||
